CREATE TABLE "genre" (
    "id" BIGSERIAL PRIMARY KEY,
	"name" VARCHAR(255) UNIQUE NOT NULL,
	"created_time" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_time" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);