CREATE TABLE "tag" (
    "id" BIGSERIAL PRIMARY KEY,
	"name" VARCHAR(20) NOT NULL,
	"is_deleted" BOOLEAN DEFAULT FALSE NOT NULL,
	"created_time" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_time" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);